server.port=1018
spring.datasource.url=jdbc:postgresql://localhost:5432/games
spring.datasource.username=postgres
spring.datasource.password=w5bf3xxx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true